### ISSUE TITLE
테스트용 이슈

### ISSUE THREAD

**Issue by yarogono** [D0ryeon/Breaking_CyberPsycho#1]
# 스타트씬 게임 시작 버튼 구현
- [x] 게임 시작 버튼 디자인
- [x] 게임 시작 버튼 클릭 시 이벤트

**Comment by yarogono** [comment]
@HOHOJO @D0ryeon @IAK0401  멘션 테스트입니다.

**Comment by D0ryeon** [comment]
@yarogono 코멘트 테스트입니다~
